### ISSUE TITLE
Question regarding verbose logs upon CT fetcher startup

### ISSUE THREAD

**Issue by d-Rickyy-b** [google/certificate-transparency-go#1030]
Hi there,

this is more of a question than an actual issue. When starting my application and all the workers for the individual CT logs, I get a lot of log spam:

```
I0129 21:46:18.176929   26552 fetcher.go:123] https://ct.googleapis.com/logs/us1/argon2024: Reset EndIndex from 0 to 17546767
I0129 21:46:18.196232   26552 fetcher.go:120] https://ct.googleapis.com/logs/argon2022: Got STH with 1602370828 certs
I0129 21:46:18.196232   26552 fetcher.go:123] https://ct.googleapis.com/logs/argon2022: Reset EndIndex from 0 to 1602370828
I0129 21:46:18.212967   26552 fetcher.go:120] https://yeti2023.ct.digicert.com/log: Got STH with 106052098 certs
I0129 21:46:18.212967   26552 fetcher.go:123] https://yeti2023.ct.digicert.com/log: Reset EndIndex from 0 to 106052098
I0129 21:46:18.217095   26552 fetcher.go:120] https://yeti2022.ct.digicert.com/log: Got STH with 66539807 certs
I0129 21:46:18.217095   26552 fetcher.go:123] https://yeti2022.ct.digicert.com/log: Reset EndIndex from 0 to 66539807
I0129 21:46:18.229944   26552 fetcher.go:120] https://yeti2025.ct.digicert.com/log: Got STH with 563 certs
I0129 21:46:18.229944   26552 fetcher.go:123] https://yeti2025.ct.digicert.com/log: Reset EndIndex from 0 to 563
I0129 21:46:18.233930   26552 fetcher.go:120] https://yeti2024.ct.digicert.com/log: Got STH with 14413348 certs
I0129 21:46:18.233930   26552 fetcher.go:123] https://yeti2024.ct.digicert.com/log: Reset EndIndex from 0 to 14413348
I0129 21:46:18.573582   26552 fetcher.go:120] https://ct.trustasia.com/log2022: Got STH with 1548183 certs
I0129 21:46:18.573582   26552 fetcher.go:123] https://ct.trustasia.com/log2022: Reset EndIndex from 0 to 1548183
I0129 21:46:18.580210   26552 fetcher.go:120] https://ct.trustasia.com/log2023: Got STH with 292810 certs
I0129 21:46:18.580210   26552 fetcher.go:123] https://ct.trustasia.com/log2023: Reset EndIndex from 0 to 292810
I0129 21:46:18.762320   26552 fetcher.go:120] https://ct2024.trustasia.com/log2024: Got STH with 32005 certs
I0129 21:46:18.762320   26552 fetcher.go:123] https://ct2024.trustasia.com/log2024: Reset EndIndex from 0 to 32005
...
```

This is due to these lines of code:
https://github.com/google/certificate-transparency-go/blob/3f5a6e9d6893a142928648d26e9cf53a6d4a449e/scanner/fetcher.go#L120-L123

Now my questions are:
1. Do you know of a way how to configure the klog library to only log specific log levels? I read about `-v`, but i have no such flag specified for my CLI
2. Do you think the lib needs to be that verbose by default when starting up the log workers?

Cheers,
Rico

**Comment by mhutchinson** [comment]
Hi Rico, thanks for the report. I've downgraded this logging to verbose. Any client that wishes to see this would be able to supply `--v=1` to their command line arguments if the logging flags are available. In my practice I've seen this happen to any code that imports glog or klog, but it could be that there are subtleties that prevent this happening if you're not seeing the `v` flag supported in your application.

**Comment by d-Rickyy-b** [comment]
Hi Martin, thank you for the help.

Regarding the `--v=1` flag: I am using CLI flags myself ([https://github.com/d-Rickyy-b/certstream-server-go/blob/056859cbb5dcdd953badb4153134083fa7d92a11/cmd/main.go#L14-L18](click)). So the passed flags will be evaluated by the `flags.Parse()` in my code and there I do not define any `--v` flag, so I get an error that `--v` is not a valid flag. 

So I assume if I did not define flags at all, I wouldn't run into issues. I might try that at some point.
