### ISSUE TITLE
trillian/ctfe: Prevent STH being used for fingerprinting users

### ISSUE THREAD

**Issue by rolandshoemaker** [google/certificate-transparency-go#105]
Currently each time a STH is retrieved via get-sth a new signature is created and since CT almost always uses ECDSA these signatures are non-deterministic. This means that when the STH doesn't change between signatures it can be used to uniquely fingerprint the user that retrieved it. It seems like there are two solutions to this problem:

* Use RFC6979 deterministic ECDSA signatures
* Cache the STH

The first seems like a lot of work, although perfectly doable and would allow the CTFE to continue being essentially stateless while the second seems a lot simpler but does require some more significant architectural changes as well as giving the CTFE more information about how the Trillian log signer operates.

**Comment by AlCutter** [comment]
There are other potential solutions too:
e.g. a deterministic function which looks at each Trillian STH, and determines whether it should be promoted to a CT STH (noddy example: `TrillianSTH.RootHash%n == 0`) - this should result in tuneably fewer STHs being emitted by the Log.  And since the function is deterministic, each CTFE would naturally promote the same selection of Trillian STHs without requiring any form of coordination. (I can see a few wrinkles in here, but it's an avenue of thought at least.)

**Comment by daviddrysdale** [comment]
So I guess there are two factors that make STHs more individually identifiable for Trillian than for previous log implementations:
 a) The Trillian logsigner runs very frequently, and so issues STH more frequently & with finer granularity (i.e. smaller gap in tree size between one STH and the next).
 b) The CTFE re-signs every time it is asked for an STH.

An initial pair of simplistic things to do might be to:
 a) Increase the `--sequencer_interval` for the logsigner to something larger (5m?)
 b) Have each CTFE instance locally cache the last-sth **signature**, and re-use the signature if the Trillian backend returns the same log root as previously.

Those are both easy to do, but are they enough to reduce the fingerprinting concerns?

**Comment by AlCutter** [comment]
Simple-thing-do-to-(a) will only work if there are fewer than _batch_size_ certs coming along within whatever value you set `--sequencer_interval` to, I think. In the case where there's more work to do that can be done in one batch, the sequencer should be busy looping until it's cleared the backlog, and that'll produce a series of Trillian STHs in quick succession.

**Comment by Martin2112** [comment]
Do we think the STH cache is enough for the moment or should we do more?

**Comment by paulmattei** [comment]
@rolandshoemaker running through our backlog. Per Martin's comment, is the STH cache sufficient? Thanks!

**Comment by rolandshoemaker** [comment]
Seems like a reasonable solution to me.

**Comment by pavelkalinnikov** [comment]
Closing. Will re-open if STH cache becomes insufficient.
