### ISSUE TITLE
Remove lint exceptions and fix remaining issues

### ISSUE THREAD

**Issue by mhutchinson** [google/certificate-transparency-go#1065]
https://github.com/google/certificate-transparency-go/blob/master/.golangci.yaml#L22 has an exclusion in place for errors that are discarded: https://golangci-lint.run/usage/false-positives/#exc0001

#1064 fixed a lot of similar errors, but these remaining ones are still to be fixed.

- [ ] Remove the exception from `.golangci.yaml`
- [ ] Run `golangci-lint run`
- [ ] Fix the errors until the linter is happy
- [ ] Submit PR
- [ ] Enjoy the satisfaction of making the world a slightly better place

**Comment by silaselisha** [comment]
@mhutchinson a polite request, I would like to work on this issue.

**Comment by roger2hk** [comment]
> @mhutchinson a polite request, I would like to work on this issue.

You're welcome to create pull requests and link to this issue.

**Comment by roger2hk** [comment]
Fixed in #1438.
