### ISSUE TITLE
CTFE GLIBC Error

### ISSUE THREAD

**Issue by myatsko-1** [google/certificate-transparency-go#1118]
I'm trying the [Docker deployment](https://github.com/google/certificate-transparency-go/tree/master/trillian/examples/deployment/docker/ctfe) on a Amazon Linux server. When I run docker-compose --profile frontend up, it successfully launches the ctfe-db, ctfe-trillian-log-server-1, and ctfe-trillian-log-signer-1 containers. But, I keep getting 'exited with code 1' when it tries to launch the ctfe-ctfe-1 container:

ctfe-ctfe-1                 | /ct_server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /ct_server)
ctfe-ctfe-1                 | /ct_server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /ct_server)

Any ideas how to get past this error?

**Comment by roger2hk** [comment]
@myatsko-1 Please try again. The latest ctfe Docker image in gcr.io/trillian-opensource-ci/ctfe should have this issue fixed.

**Comment by myatsko-1** [comment]
Thank you. That resolved the issue. I’ll submit another issue shortly with some suggested updates to the Dockerized Test Deployment <https://github.com/google/certificate-transparency-go/tree/master/trillian/examples/deployment/docker/ctfe> instructions based on my recent experience.

**Comment by roger2hk** [comment]
I'm glad that the fix resolved your issue. I found some other issues with the instructions when I tried to replicate this issue. Please feel free to submit new issues or pull requests to update the deployment documentation.
