### ISSUE TITLE
Compilation Failure on `GOOS=aix`

### ISSUE THREAD

**Issue by mohammed90** [google/certificate-transparency-go#1276]
We have received a report of compilation failure with `GOOS` is `aix` (see caddyserver/caddy#5970). The build failure reports the following:

```
# github.com/google/certificate-transparency-go/x509
../../../../go/pkg/mod/github.com/google/certificate-transparency-go@v1.1.6/x509/cert_pool.go:65:9: undefined: loadSystemRoots
../../../../go/pkg/mod/github.com/google/certificate-transparency-go@v1.1.6/x509/root.go:21:32: undefined: loadSystemRoots
../../../../go/pkg/mod/github.com/google/certificate-transparency-go@v1.1.6/x509/verify.go:759:12: c.systemVerify undefined (type *Certificate has no field or method systemVerify)
```

The 3 errors listed in the error message report functions/methods that are defined in `root_unix.go`. The [build tags](https://github.com/google/certificate-transparency-go/blob/df496fc651394b4aa5ab529b8bc35010c3d282e4/x509/root_unix.go#L5-L6) exclude `AIX`. I believe the extensive list can be replaced with the new `unix` build tag (implemented here https://github.com/golang/go/commit/c3fcd0117784ac05e35120ac0de6c960b400a31e) that will include any Unix-like system by default. This avoids such hassles in the future. FWIW, AIX supports [`SSL_CERT_DIR`](https://www.ibm.com/docs/en/search/SSL_CERT_DIR?scope=ssw_aix_73) and [`SSL_CERT_FILE`](https://www.ibm.com/docs/en/search/SSL_CERT_FILE?scope=ssw_aix_73) if you prefer to be explicit about the supported OS.

**Comment by roger2hk** [comment]
The caddyserver/caddy has a indirect dependency on this repo. Note that the `x509` folder in this repo is a weaken forked version of the go/crypto/x509. According to the dependency tree, I will create an issue or a pull request in google/go-tspi to see if there is a strong reason to rely on this repo's x509 version.

**Comment by roger2hk** [comment]
The issue (https://github.com/golang/go/issues/30416) to support for parsing certificates with RSAES-OAEP public keys in crypto/x509 is still open. 😕

https://github.com/google/go-tspi/blob/68e5e7a4206b89249f71ec492f15c19edd3a5061/verification/verification.go#L140-L145
