### ISSUE TITLE
trillian/ctfe: certs issued by name-constrained CAs can't be logged

### ISSUE THREAD

**Issue by acohn** [google/certificate-transparency-go#134]
I was recently attempting to log a certificate issued by a name-constrained CA to Argon, and I got this error: "x509: a root or intermediate certificate is not authorized to sign in this domain". I believe this behavior is incorrect.

If you need an example certificate that fails, here's [300k](https://censys.io/certificates?q=parsed.extensions.authority_key_id%3A59101a9df7d83734fdadd50bac68ae02f7a0bd83+and+tags.raw%3Atrusted) of them. You could also try the certificate currently used by https://vt.edu/.

It looks like the Go x509 library refuses to verify certificates from name-constrained CAs unless the DNSName was supplied in the verification options. (https://github.com/golang/go/issues/15196#issuecomment-313900019 alludes to this behavior) Since the CTFE doesn't do that, it fails to log these certificates. This was fixed in golang/go@9e76ce70701ceef8fbccfb953b33a2ae7fe0367c, which should be released as part of Go 1.10.

**Comment by daviddrysdale** [comment]
OK, we [normally merge](https://github.com/google/certificate-transparency-go/pull/94) upstream `x509` fixes after they're released, but it sounds like we might want to cherry-pick some changes before then -- thanks for the heads up.
