### ISSUE TITLE
Fails to build with go1.10 darwin/amd64

### ISSUE THREAD

**Issue by bcessa** [google/certificate-transparency-go#153]
Just update to go 1.10 and a project using this as a dependency fails to build

Dependency config:
```toml
[[projects]]
  branch = "master"
  name = "github.com/google/certificate-transparency-go"
  packages = [
    ".",
    "asn1",
    "client",
    "client/configpb",
    "jsonclient",
    "tls",
    "x509",
    "x509/pkix"
  ]
  revision = "686d1c84287487373dd38c9faaf05aa79acacf26"
```

Build error:
```sh
# vendor/github.com/google/certificate-transparency-go/x509
vendor/github.com/google/certificate-transparency-go/x509/root_cgo_darwin.go:224: cannot use nil as type _Ctype_CFDataRef in assignment
vendor/github.com/google/certificate-transparency-go/x509/root_cgo_darwin.go:225: cannot use nil as type _Ctype_CFDataRef in assignment
vendor/github.com/google/certificate-transparency-go/x509/root_cgo_darwin.go:235: cannot convert nil to type _Ctype_CFDataRef
make: *** [build] Error 2
```

Go version:
```sh
go version go1.10 darwin/amd64
```

Appears to be related to #131 but it's already closed

**Comment by aambati** [comment]
@daviddrysdale has this change been merged? I don't see this commit in the commit history, so wondering?

**Comment by daviddrysdale** [comment]
Yeah, the change is [in the current code](https://github.com/google/certificate-transparency-go/blob/master/x509/root_cgo_darwin.go#L225) -- are you sure that the vendored version of the code is up-to-date too?

**Comment by aambati** [comment]
yes

**Comment by daviddrysdale** [comment]
The line numbers in the error message you provided don't match the current code (but do match [an earlier version of the code](https://github.com/google/certificate-transparency-go/blob/14310324e16300bc87f9278caea306136ad7c7f3/x509/root_cgo_darwin.go#L210)).

**Comment by aambati** [comment]
so, i was able to compile after running "govendor fetch golang.org/x/crypto/cryptobyte" with Go 1.10..but it errors out with Go 1.9
