### ISSUE TITLE
Build failure on 32bit systems

### ISSUE THREAD

**Issue by gibmat** [google/certificate-transparency-go#1539]
Attempting to build on a 32bit system fails:

```
# github.com/google/certificate-transparency-go/client_test [github.com/google/certificate-transparency-go/client.test]
src/github.com/google/certificate-transparency-go/client/logclient_test.go:289:61: cannot use ValidSTHResponseTimestamp (untyped int constant 1396609800587) as int value in argument to t.Errorf (overflows)
FAIL	github.com/google/certificate-transparency-go/client [build failed]
# github.com/google/certificate-transparency-go/x509 [github.com/google/certificate-transparency-go/x509.test]
src/github.com/google/certificate-transparency-go/x509/rpki_test.go:246:20: cannot use 0x00ffffffff (untyped int constant 4294967295) as int value in struct literal (overflows)
src/github.com/google/certificate-transparency-go/x509/rpki_test.go:276:20: cannot use 0x00ffffffff (untyped int constant 4294967295) as int value in struct literal (overflows)
FAIL	github.com/google/certificate-transparency-go/x509 [build failed]
```

(Full log from Debian's autopkgtest infrastructure [available here](https://ci.debian.net/packages/g/golang-github-google-certificate-transparency/testing/i386/49696706/).)

It's trivial to add explicit casts to `int64`, but due to the CLA requirement I won't be submitting a pull request fixing this.

**Comment by roger2hk** [comment]
Thanks for reporting this issue. I've created #1540 to fix this.

**Comment by roger2hk** [comment]
@gibmat The pull request was merged. It doesn't fix the root cause but the 32-bit OS will not run the rpki tests. Do you need a release to get this unblocked on the CI tests?

**Comment by gibmat** [comment]
Thanks! There's no need for quick release as I've worked around the problem for now. When the next release is made Debian will pickup the changes.
