### ISSUE TITLE
Incomplete vendor folder

### ISSUE THREAD

**Issue by FiloSottile** [google/certificate-transparency-go#162]
When building `./preload/preloader`, the following packages are missing:

github.com/gogo/protobuf/proto
github.com/golang/protobuf/proto
github.com/golang/protobuf/ptypes
github.com/golang/protobuf/ptypes/timestamp
golang.org/x/net/context/ctxhttp

I suggest using dep for vendoring. It might be as easy as running `dep init`, which worked perfectly for me, and reduced the vendor folder size, too. It only updated github.com/coreos/etcd and github.com/grpc-ecosystem/grpc-gateway/runtime.

**Comment by daviddrysdale** [comment]
So far, we've gotten away with only vendoring the things we absolutely had to (and have done so manually), so I think we normally pull in the current versions of those particular packages (e.g. via the various `go get` lines in `.travis.yml`).

I suspect a vendoring tool will become inevitable at some point, and given that `dep` is aiming to become part of the standard toolchain, that seems the sensible choice.

**Comment by FiloSottile** [comment]
Agreed, full vendoring is also critical for reproducibility. As things
are it's impossible to build a binary as it was a month ago, an issue
that bit me in the context of Trillian.
(As for dep becoming standard, you should know that vgo (introduced this
week) will probably be the final tool, but dep is officially supported,
so the transition will be smooth, and I think vgo is way too young to
adopt right now.)

**Comment by jsha** [comment]
Any further thoughts on vendoring? I agree with @FiloSottile that vendoring is really important for reproducibility, which is particularly important for Trillian deploys, where a broken deploy can result in a log disqualification.

If the maintainers are amenable, I'd be willing to put together a PR adding vendoring with `dep`.

**Comment by Martin2112** [comment]
I think we're usually fairly relaxed about other people doing work :-) Seriously, dep looks like the way forward at the moment.

**Comment by daviddrysdale** [comment]
[Hmm](https://github.com/golang/dep/issues/1959):
"Once Go 1.11 is out, it really makes very little sense for a new project not already using dep to start using it."

**Comment by FiloSottile** [comment]
Modules are still an experiment, but they are able to transition dep metadata on the fly, so don’t let this stop you from adopting a solution. Every release you make without dep or modules is a release that can never be reproduced.

**Comment by pavelkalinnikov** [comment]
Is this now obsolete as we use modules?
