### ISSUE TITLE
trillian/ctfe: Debug and metrics endpoints are exposed on API endpoint

### ISSUE THREAD

**Issue by rolandshoemaker** [google/certificate-transparency-go#18]
Which requires URL filtering if the operator wants to hide potentially sensitive information. Probably a separate listener should be used for the various debug/prom endpoints instead.

**Comment by daviddrysdale** [comment]
Good point, it should be possible to hide that -- and fiddling with URLs to do so sounds pesky.

Would something like the following (in `trillian/ctfe/ct_server/main.go`)
```go
metricsEndpoint   = flag.String("metrics_endpoint", "",
                                "Endpoint for serving metrics; if left blank, metrics will be visible on --http_endpoint")
```
(and associated plumbing) cover this for you?

**Comment by rolandshoemaker** [comment]
Yup, sounds like the best solution to me.
