### ISSUE TITLE
CANotAuthorizedForExtKeyUsage problem with Trillian logs

### ISSUE THREAD

**Issue by robstradling** [google/certificate-transparency-go#197]
Both https://ct.googleapis.com/logs/argon2020/ct/v1/add-pre-chain and https://ct.cloudflare.com/logs/nimbus2020/ct/v1/add-pre-chain reject the submission below.  The error message is "x509: a root or intermediate certificate is not authorized for an extended key usage: EKU not permitted: asn1.ObjectIdentifier{2, 16, 840, 1, 113741, 1, 2, 3}".

The intermediate certificate contains 2 EKU OIDs: serverAuth and clientAuth.
The leaf certificate contains 3 EKU OIDs: serverAuth, clientAuth and 2.16.840.1.113741.1.2.3.

I believe submissions of this sort should be accepted.  I'm not aware of any browser that would reject this chain, and AFAICT it doesn't violate any RFC5280 rules.

`{"chain":["MIIFYzCCBEugAwIBAgIQQzf/4JkQvNGXkeOd4uPCtTANBgkqhkiG9w0BAQsFADCBizELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEaMBgGA1UEChMRQ09NT0RPIENBIExpbWl0ZWQxMTAvBgNVBAMTKENPTU9ETyBTSEEtMiBQcm8gU2VyaWVzIFNlY3VyZSBTZXJ2ZXIgQ0EwHhcNMTgwMzI4MDAwMDAwWhcNMjAwNjI1MjM1OTU5WjBEMSEwHwYDVQQLExhEb21haW4gQ29udHJvbCBWYWxpZGF0ZWQxHzAdBgNVBAMTFndlYm1haWwuYmxpdHp2ZXJsYWcuZGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCevQmeLZdssLoq1wxfXS2DyHBXrNquLoPolAcSDi4edMfYPG0in+l2zNh/LZbgpULZX2rRYV2cGPJBSx15ini56Kv4EX7RjPH6JYxCIgNCCcN1LPdsgHjpo5Gj7M+C8FRG7hHFpqf1EzEK+rfQJm3rZdj6BGO2vq41Hha+hiK5aBWj6HDn95+0Km7HwadPiRV7iXHUnjKjU6iP0bZ/i12lhVL5aTHt0iHAwXVj29teVmWoZ0G0dGNQKroaac/fjrW+N0DgHbaeb6YoVTRdmOCzucSl40FGjZO8tBIG6a/Kbgf9PdS0LL8PBC0qdNVa6hT0aarQCjwCEZloFRjlGQC7AgMBAAGjggIHMIICAzAfBgNVHSMEGDAWgBSAtisNQAoP3z+kv78D9LF2a9XnjzAdBgNVHQ4EFgQUGGZGLNPDTZDmbVQlRuBmB1igOHkwDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB/wQCMAAwKQYDVR0lBCIwIAYIKwYBBQUHAwEGCCsGAQUFBwMCBgpghkgBhvhNAQIDMFAGA1UdIARJMEcwOwYMKwYBBAGyMQECAQMEMCswKQYIKwYBBQUHAgEWHWh0dHBzOi8vc2VjdXJlLmNvbW9kby5uZXQvQ1BTMAgGBmeBDAECATBPBgNVHR8ESDBGMESgQqBAhj5odHRwOi8vY3JsLmNvbW9kb2NhLmNvbS9DT01PRE9TSEEtMlByb1Nlcmllc1NlY3VyZVNlcnZlckNBLmNybDCBgAYIKwYBBQUHAQEEdDByMEoGCCsGAQUFBzAChj5odHRwOi8vY3J0LmNvbW9kb2NhLmNvbS9DT01PRE9TSEEtMlByb1Nlcmllc1NlY3VyZVNlcnZlckNBLmNydDAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuY29tb2RvY2EuY29tMD0GA1UdEQQ2MDSCFndlYm1haWwuYmxpdHp2ZXJsYWcuZGWCGnd3dy53ZWJtYWlsLmJsaXR6dmVybGFnLmRlMBMGCisGAQQB1nkCBAMBAf8EAgUAMA0GCSqGSIb3DQEBCwUAA4IBAQCky5AVMHbFLUxgDwdKEmOGHaXWYoroMvx/0qvGrPAdE186ytx8op7InuEWTX+GhIzjd2ynR60GY2DozBm2xZyf5WdL4Q7CXhXnqS/3DchM9t5B7NoaJYhTL+LHGq4j3xLrerpA+ffYGwqnCuK8rZdZPDCW8VSL50ATJHp8osyuAiJaqZsAhzgTvA5JOOxM8VZd7UdCOiMQTLx2sgoLlDx99sCcM6VS5wtqGla2MTOM68BlQkerK5x6XaEQaCWCW/TMBk62DmSQJxLwuqRgXDFVwMnjJBsGFATQ286BuNjjQtKeSKgNz5LgjVbZXncFcaBdLfcVAH9A/XHxG3+SeMwM","MIIEszCCA5ugAwIBAgIRALm8Dvlxug7myHs2fXKPFsMwDQYJKoZIhvcNAQEMBQAwezELMAkGA1UEBhMCR0IxGzAZBgNVBAgMEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBwwHU2FsZm9yZDEaMBgGA1UECgwRQ29tb2RvIENBIExpbWl0ZWQxITAfBgNVBAMMGEFBQSBDZXJ0aWZpY2F0ZSBTZXJ2aWNlczAeFw0xNTAyMTIwMDAwMDBaFw0zMDAyMTEyMzU5NTlaMIGLMQswCQYDVQQGEwJHQjEbMBkGA1UECBMSR3JlYXRlciBNYW5jaGVzdGVyMRAwDgYDVQQHEwdTYWxmb3JkMRowGAYDVQQKExFDT01PRE8gQ0EgTGltaXRlZDExMC8GA1UEAxMoQ09NT0RPIFNIQS0yIFBybyBTZXJpZXMgU2VjdXJlIFNlcnZlciBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKfDF7ksP98PglnEw+2reeiYfnyLHnFh6nHteiwESpgltt6C6LZs3DO3Kjd0ZLutEhY1slAt2+26sHAsy2kA+OIDxwW3n06ScYQHP3lCZuhjMuUT+id2gcJhtzlvag+MiPgUyIWJS6YRsnlOtRR0gIJj4yyBiexPVHUmgBgF5UjJWaL/2V99mrfvIZdTkcuF0e9sW8FyChyz0LA5YLlWCAXM+0OOCBv6sbxSrcT8VO/tR3+LDssPoOZ2Id/YHF+T4CXUtZ7uCC9/DQhXEx5nKHffKoCokzHxVR35+VeSEu2bfiGxhWR4gYd7dm3reN91ORIMStG5npyxE0NqMg6kKRkCAwEAAaOCAR8wggEbMB8GA1UdIwQYMBaAFKARCiM+lvEH7OKvKe+CpX/QMKS0MB0GA1UdDgQWBBSAtisNQAoP3z+kv78D9LF2a9XnjzAOBgNVHQ8BAf8EBAMCAYYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwGwYDVR0gBBQwEjAGBgRVHSAAMAgGBmeBDAECATBDBgNVHR8EPDA6MDigNqA0hjJodHRwOi8vY3JsLmNvbW9kb2NhLmNvbS9BQUFDZXJ0aWZpY2F0ZVNlcnZpY2VzLmNybDA0BggrBgEFBQcBAQQoMCYwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmNvbW9kb2NhLmNvbTANBgkqhkiG9w0BAQwFAAOCAQEAcaRIjF1YZ7ivBA30KvRTacpH8N5bdoHYzvaF6j4vutHLvuOg8BQXB7d5+USfSp4Qr6E5SUfCvy4gnKWsKsXQH3vK/lE6nL/a8Ygh9/vT8wZxKkA/FfEIVojYQ+pSUANDcepe6BtmF0WL7Pr/03swQDBUI8VzXMuDlUVSFbPUesUOkR4h1Rmh9RVfG+mCS20queLLMcTCFJg7cz3HrViPJ/vp/YYsctfXRHoEngqg8FqvFpmaz6zEDh0Wd1odBGwAfcI/oGwSmn6zsPZ5mBfOcsxxtwyH6sLpQQidsQc1VtwUp/c6vOf8m30O32OHrKOwltKNq+CM8x+kc2suZlR4ow=="]}`

**Comment by rolandshoemaker** [comment]
Trillian uses a forked version of the stdlib `x509` lib but the chain verification behavior is mostly the same in relation to EKU checking ([fork](https://github.com/google/certificate-transparency-go/blob/master/x509/verify.go#L714-L729) code, [stdlib](https://github.com/golang/go/blob/master/src/crypto/x509/verify.go#L731-L745) code, a quick look at the change in `ekuPermittedBy` makes me think it wouldn't actually do anything differently in this case). This seems like something to be brought up on the [golang/go](https://github.com/golang/go) repo.

**Comment by daviddrysdale** [comment]
Yeah, this will be the EKU validation code that was brought in by the [sync of x509 with Go 1.10](https://github.com/google/certificate-transparency-go/pull/142); I would guess that specifically [this commit](https://github.com/golang/go/commit/647648bd475e) triggers the validation failure.

So I'd agree with @rolandshoemaker that raising this upstream would be ideal (I guess it should be easy to reproduce the validation failure with upstream `crypto/x509`) and if a fix appears there we can cherry-pick it across to speed things up.

**Comment by daviddrysdale** [comment]
https://play.golang.org/p/HeJ_NG5LQPE shows the validation failure with `crypto/x509`, although it would be nice to have a non-precertificate example.

**Comment by robstradling** [comment]
https://play.golang.org/p/ITwuMz9qN4z is the same example except that I've substituted the precertificate for the corresponding certificate.

**Comment by FiloSottile** [comment]
While we are looking at this upstream, I think the best way forward for CT would be to implement a very stripped down chain validation in the fork. The Go standard library is intentionally opinionated, while CT logs should be as broad as possible.

Anything signed by a CA (intermediate or otherwise, constrained or otherwise) private key is IMHO log-worthy anyway. It can be up to the auditors and community to decide what is issuance and what is not.

**Comment by Martin2112** [comment]
Is this fixed?
