### ISSUE TITLE
Reuse Trillian Merkle Tree verifiers

### ISSUE THREAD

**Issue by pav-kv** [google/certificate-transparency-go#227]
Proof verification code in [merkletree/](https://github.com/google/certificate-transparency-go/tree/master/merkletree) looks the same as in Trillian's [merkle/](https://github.com/google/trillian/tree/master/merkle) folder. Could we just reuse Trillian code here? Some features in Trillian are also needed in this repo, e.g. [range inclusion verification](https://github.com/google/trillian/pull/1108) will be used in Migrillian to verify the fetched batches.

**Comment by pavelkalinnikov** [comment]
Started the refactoring in #228.

**Comment by RJPercival** [comment]
Did #228 fix this?
