### ISSUE TITLE
`ct.SignedCertificateTimestamp` missing JSON struct tags

### ISSUE THREAD

**Issue by cpu** [google/certificate-transparency-go#255]
Hi folks :wave:,

While implementing a mock CT server for some tests using this project I noticed the `ct.SignedCertificateTimestamp` type from `types.go` is missing `json` struct tags:
https://github.com/google/certificate-transparency-go/blob/a961b728bb4444704ae1947ea0496ce7563c3705/types.go#L292-L301

The RFC 6962 sections referenced in that comment (3.2, 4.1 and 4.2) provide JSON encoded responses. In my own code I work around this by creating a throw-away type with the required JSON tags but it seems like this type could provide the tags itself and save users some work :-)

**Comment by cpu** [comment]
I submitted a small PR to address this issue in https://github.com/google/certificate-transparency-go/pull/256. Thanks!

**Comment by daviddrysdale** [comment]
The client and server code use the `ct.AddChainResponse` type, which has JSON tags, but I don't immediately recall why it's a separate type from `ct.SignedCertificateTimestamp`...

**Comment by cpu** [comment]
After discussion with @daviddrysdale on #256 it seems like [there is reason](https://github.com/google/certificate-transparency-go/pull/256#discussion_r191713874) to maintain the two separate types and in this case for marshalling to JSON the best choice is to use `ct.AddChainResponse`.

Thanks for the guidance!
