### ISSUE TITLE
trillian/ctfe misinterprets how trillians GetLeavesByIndex works

### ISSUE THREAD

**Issue by rolandshoemaker** [google/certificate-transparency-go#257]
CTFE thinks that trillians GetLeavesByIndex RPC will return a non-error response when the requested range is higher than the current tree size and that it can check the response itself for this case, this is incorrect and causes 500s.

(Tracking reference in Trillian for a possible better case is: google/trillian#1162).

**Comment by Martin2112** [comment]
I think Gary is working on this?

**Comment by Martin2112** [comment]
No the change Gary did was to a different API. I thought this behaviour might have recently changed.

**Comment by Martin2112** [comment]
The PR I just did on the other repo will return a GRPC status code OutOfRange and CTFE will automatically map this to a 4xx error assuming it gets merged.

**Comment by Martin2112** [comment]
I believe the logserver change I just merged will fix this.
