### ISSUE TITLE
trillian/ctfe: add support for 'freezing' a log

### ISSUE THREAD

**Issue by rolandshoemaker** [google/certificate-transparency-go#277]
Basically a simple config option to turn a log read-only. Probably the easiest way to do this would be to add a quick check in `addChainInternal` along the lines of `if frozen { return http.StatusBadRequest, errors.New("log is read-only") }`.

**Comment by daviddrysdale** [comment]
Isn't this [already supported](https://github.com/google/certificate-transparency-go/blob/master/trillian/integration/ct_integration.go#L745-L758)?

**Comment by Martin2112** [comment]
Yes it's supported and there's an integration test for it. Documented here:

https://github.com/google/trillian/blob/master/docs/howto/freeze_a_ct_log.md

**Comment by rolandshoemaker** [comment]
Ah, didn't realize this was done at the backend, thanks for the pointer!
