### ISSUE TITLE
windows/go-1.11 compile error

### ISSUE THREAD

**Issue by kolyshkin** [google/certificate-transparency-go#284]
I am seeing the following error trying to use this package on Windows using go-1.11beta1:

> 13:11:05 ....\vendor\github.com\google\certificate-transparency\go\x509\root_windows.go:112:3: cannot use uintptr(unsafe.Pointer(sslPara)) (type uintptr) as type syscall.Pointer in field value

This is apparently caused by the following change in golang: https://github.com/golang/go/commit/4869ec00e87ef49db2646c25d28d5c7e4f1caff8

and requires a one-line fix identical to the one in here: https://github.com/golang/go/commit/4869ec00e87ef49db2646c25d28d5c7e4f1caff8?diff=unified#diff-9a0dd81b66ea632b270ed4c40cb71e43

which of course will break compilation with golang < 1.11, so a more complicated fix is required.

Found while trying to compile Docker with go-1.11beta1 on Windows (https://github.com/moby/moby/pull/37358#issuecomment-401923825)

**Comment by kolyshkin** [comment]
Proposed solution is https://github.com/google/certificate-transparency-go/pull/285

An alternative would be a branch that only supports go >= 1.11, which might be a better way wrt maintainership.

**Comment by daviddrysdale** [comment]
I had a quick stab at a slightly different solution in #286, which doesn't need type aliases. 

However, I've only (cross-)compiled with 1.10 so far, so it's not yet tested.

**Comment by daviddrysdale** [comment]
@kolyshkin,  does #286 work for you?   (And thanks for spotting/raising/fixing)

**Comment by thaJeztah** [comment]
Thanks @daviddrysdale!

**Comment by kolyshkin** [comment]
> @kolyshkin, does #286 work for you? (And thanks for spotting/raising/fixing)

It's hard to test for me as the package is vendored, but I'll try.

As to which approach is simpler, It depends on whether this package wants to support go < 1.9 -- if yes, yours is the way to go, if no, mine looks a bit simpler. I have also left some comments in your PR.

**Comment by thaJeztah** [comment]
> It's hard to test for me as the package is vendored, but I'll try.

If needed, you can temporarily vendor from @daviddrysdale's fork for testing;

```
github.com/google/certificate-transparency 044b82e886027e178628195049ef441907a87268 https://github.com/daviddrysdale/certificate-transparency-go.git

**Comment by gavin-shakespeare** [comment]
Thanks a lot. I have fixed this issue after reading this page.
