### ISSUE TITLE
Database error from Trillian demo-script 

### ISSUE THREAD

**Issue by ricketybridge** [google/certificate-transparency-go#299]
Although I configured my database not to have a password for the user `test@localhost`, I'm getting the following error when running `./demo-script.sh` in `/trillian/integration`:

`W0723 15:28:42.047124    8336 tree_storage.go:81] Failed to set strict mode on mysql db: Error 1045: Access denied for user 'test'@'localhost' (using password: YES)`

(To be more specific, I set the password to the empty string, which appears to be the closest MySQL can get to not having a password. At any rate, the command `mysql --host=127.0.0.1 --port=3306` successfully connects.)

I then get this error, which I assume is due to the first one (or due to the same cause as the first one):

`E0723 15:28:50.232953    8348 admin.go:57] Admin server unavailable: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp [::1]:6962: connect: connection refused"`

**Comment by AlCutter** [comment]
Did you update `demo_script.sh` to set a new password-less mysql URI string with `--mysql_uri` too?

If not, it'll try to use the [default one](https://github.com/google/trillian/blob/master/server/mysql_storage_provider.go#L32) which does have a password set, this would perhaps example the `Access denied ... (Using password: YES)` message.

**Comment by ricketybridge** [comment]
No. Somehow I deleted the password "zaphod" in resetdb.sh. When I changed it back to how it was originally, it worked. We can close this issue.
