### ISSUE TITLE
Invalid SCTs for PreCerts

### ISSUE THREAD

**Issue by Martin2112** [google/certificate-transparency-go#39]
We've seen some evidence that Trillian CTFE is generating SCTs for pre-certs that are not valid. This is being investigated.

**Comment by daviddrysdale** [comment]
[RFC 6962 s3.1](https://tools.ietf.org/html/rfc6962#section-3.1) allows pre-certs to be signed by an additional special-purpose intermediate cert, that has 1.3.6.1.4.1.11129.2.4.4 as an extended key usage.

For a chain PreCert-B-A-Root (where B is the special-purpose intermediate cert), this leads to the question of whether A or B should be treated as the issuer (for the `issuer_key_hash` field in the `PreCert` part of the SCT ([s3.2](https://tools.ietf.org/html/rfc6962#section-3.1))? 

The current Go code assumes B, as the that's the cert whose `Subject` field matches the `Issuer` field of the PreCert.

However, it should be A instead, as per the C++ code [uses](https://github.com/google/certificate-transparency/blob/master/cpp/log/cert_checker.cc#L204-L219).  

Also, when preparing a pre-cert for inclusion we should change the issuer name to the final issuer ("*the TBSCertificate also has its issuer changed to that of the CA that will issue the final certificate.*") as well as removing the poison ([C++ code](https://github.com/google/certificate-transparency/blob/master/cpp/log/cert_checker.cc#L226-L233)).

Aside: the net of these shenanigans is that a user can check a cert with an embedded SCT is indeed included in the log:
 - Extract the `TBSCertificate` from the signed certificate
      - Note that it's `issuer` field identifies intermediate A, the true issuer
 - Remove the SCT extension from the `TBSCertificate`
 - Build a [Merkle tree leaf](https://tools.ietf.org/html/rfc6962#section-3.4) using:
    - `version`=1, `leaf_type`=0
    - the `timestamp` from the SCT
    - log `entry_type`=1 (`precert_entry`)
    - `issuer_key_hash` from the issuer's public key
    - `tbs_certificate` as above.
 - This matches what was inserted in the log on receipt of the original add-pre-chain request, where the pre-certifcate was modified:
    - to remove the CT poison extension
    - to have the final issuer name
    - to just use the inner `TBSCertificate`.

**Comment by AlCutter** [comment]
#47 should fix this

**Comment by daviddrysdale** [comment]
Combination of #40, #45, #47 and #49 should hopefully fix this...

**Comment by Martin2112** [comment]
Among our PRs are ....
