### ISSUE TITLE
CTFE has no /healthz endpoint

### ISSUE THREAD

**Issue by RJPercival** [google/certificate-transparency-go#433]
Trillian has a /healthz endpoint that returns HTTP 200 OK and the string "ok" when it is ready to serve. The CTFE does not. It would be nice, for consistency at least, if it did. It appears that both "/" and "/metrics" are used in varying places as a substitute.

**Comment by AlCutter** [comment]
Added a simple endpoint, but it still needs to be wired up to tell the truth.
