### ISSUE TITLE
How many request QPS of each ctfe api and how big mysql is necessary 

### ISSUE THREAD

**Issue by sanerzheng** [google/certificate-transparency-go#436]
I'm a beginner of certificate-transparency. And i need to deploy a full ct-log server (not in aws, google cloud etc.), it must be support to store 3 billon logs at least. But i have no idea about how many QPS of each ctfe api such as add-chain, get-sth, get-proof-by-hash and so on will be requeired in a general ct log server. Is there anyone who has experience could help me ？and another problem is if a general Mariadb(mysql) can support these logs store and requests. if not，could anyone give me some other suggestions about DB in ct-log？ Thanks ！

the ctfe apis:
```
	AddChainPath          = "/ct/v1/add-chain"
	AddPreChainPath       = "/ct/v1/add-pre-chain"
	GetSTHPath            = "/ct/v1/get-sth"
	GetEntriesPath        = "/ct/v1/get-entries"
	GetProofByHashPath    = "/ct/v1/get-proof-by-hash"
	GetSTHConsistencyPath = "/ct/v1/get-sth-consistency"
	GetRootsPath          = "/ct/v1/get-roots"
	GetEntryAndProofPath  = "/ct/v1/get-entry-and-proof"
```

**Comment by RJPercival** [comment]
I believe other users have tested large logs on MariaDB. You'll likely need a well-provisioned database server to get good performance at that log size (SSD storage and substantial amounts of RAM, e.g. 100GB). The QPS that a CTFE will support depends on the resources available to it, but it's mostly passing requests through to Trillian so you shouldn't need many of them to handle your traffic. You should run a few of them primarily for redundancy.

**Comment by sanerzheng** [comment]
Thanks for the answer. We already test the performance of the CT system on a MariaDB with 1TB(our biggest stand-alone database server) capacity. And the whole system performance well and stably. But after insert 130 million logs successfully, the MariaDB only left about 15% capacity. I think  we will try on a distributed database to solve the capacity problem.  I will close the issue. Thanks again for the answer.

**Comment by sanerzheng** [comment]
> I believe other users have tested large logs on MariaDB. You'll likely need a well-provisioned database server to get good performance at that log size (SSD storage and substantial amounts of RAM, e.g. 100GB). The QPS that a CTFE will support depends on the resources available to it, but it's mostly passing requests through to Trillian so you shouldn't need many of them to handle your traffic. You should run a few of them primarily for redundancy.

Thanks for the answer. We already test the performance of the CT system on a MariaDB with 1TB(our biggest stand-alone database server) capacity. And the whole system performance well and stably. But after insert 130 million logs successfully, the MariaDB only left about 15% capacity. I think we will try on a distributed database to solve the capacity problem. I will close the issue. Thanks again for the answer.
