### ISSUE TITLE
Change dependency 'etcd' declared on mod to correctly point to its new place

### ISSUE THREAD

**Issue by claucece** [google/certificate-transparency-go#677]
The dependency `github.com/coreos/etcd` declared on `go.mod` have been changed to `https://github.com/etcd-io/etcd`. The mod file needs to be updated, otherwise it might cause a `	module declares its path as: go.etcd.io/etcd but was required as: github.com/coreos/etcd`

**Comment by pavelkalinnikov** [comment]
This has been fixed in #721.
