### ISSUE TITLE
Is it possible to append different type of entry signed by a CA 

### ISSUE THREAD

**Issue by ilkane** [google/certificate-transparency-go#760]
Hello,

I am wondering if it is possible to append to CT logs with a different type of data, let's say I have a data with
neither of those recognised types: (X509LogEntryType, PrecertLogEntryType or XJSONLogEntryType  ) but it is just a "Hello world" plaintext signed by a CA. Not especially asking for Trillian implementation case, but CT operators.

**Comment by pphaneuf** [comment]
I don't believe that this is possible? Chain validation code should reject it, hopefully.

**Comment by ilkane** [comment]
Thank you Pierre for your answer, 
Is it possible to test such things in a testing environment for checking the CT behaviours in one of the CT operators? Without installing my own trillian instance.

**Comment by pphaneuf** [comment]
You can request the addition of your own testing root certificate into these test logs:

https://github.com/google/certificate-transparency-community-site/blob/master/docs/google/known-logs.md#test-logs

**Comment by ilkane** [comment]
that's great thank you very much
