### ISSUE TITLE
CT v2

### ISSUE THREAD

**Issue by abadhikari** [google/certificate-transparency-go#762]
Hi,

I've been going through the code and it appears that only CT v1 data structures are supported in this repository. Will there be an update for CT v2 anytime soon?

**Comment by AlCutter** [comment]
Hi Abhinna,

Thanks for the question - do you mean the 6962bis experimental RFC? 
If so, there are no plans to do that currently.

**Comment by abadhikari** [comment]
Hi AICutter,

I appreciate you responding so quickly- yes exactly. I have noticed that within the loglist (https://www.gstatic.com/ct/log_list/v2/log_list.json), there are v2 Loggers supported by Google. Is this v2 separate from the v2 found within the 6962bis rfcs? Also are those listed loggers running the code found in this repository?

**Comment by pphaneuf** [comment]
Oh, this log list isn't a list of logs implementing v2, but rather, v2 of the log list *format*! Semantically, the v1 and v2 log list content is the same, but we used a different URL to avoid breaking software using the old format.

**Comment by abadhikari** [comment]
Ohh I see that makes a lot more sense. Thanks for the help guys!

**Comment by pphaneuf** [comment]
This repository only contains RFC6962 (non-bis) CTv1 implementations, which some (but not all) of the logs in that list use. Some logs use different implementations that the one we provide here.

No problem, you're welcome!
