### ISSUE TITLE
request: release new version

### ISSUE THREAD

**Issue by vvakame** [google/certificate-transparency-go#798]
I hope release new version of this library.

current latest release version is v1.1.1.
that contains dependency to `google.golang.org/grpc/naming` .

https://pkg.go.dev/google.golang.org/grpc/naming is removed on google.golang.org/grpc@v1.30.0 ( I don't know why this minor version update contains breaking change... )

current master/HEAD doesn't depends on it. We can update `google.golang.org/grpc`. 😸 

```
$ git checkout master
Previous HEAD position was aa25a91 Update CHANGELOG in prep for v1.1.1 release
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

$ go mod why google.golang.org/grpc/naming
# google.golang.org/grpc/naming
(main module does not need package google.golang.org/grpc/naming)

$ git checkout v1.1.1
HEAD is now at aa25a91 Update CHANGELOG in prep for v1.1.1 release

$ go mod why google.golang.org/grpc/naming
# google.golang.org/grpc/naming
github.com/google/certificate-transparency-go/trillian/ctfe/ct_server
google.golang.org/grpc/naming
```

https://github.com/duo-labs/webauthn/issues/76

**Comment by pphaneuf** [comment]
We could make a release, but it's worth noting that we started our version tags *before* Go modules were introduced and strongly recommended guidelines/rules around semantic versioning were put into place... So if we made a release, we'd either need to make it v2 (which would be rather bold and unplanned!), or we'd potentially cause breakage to other users.

Maybe you could just run `go get github.com/google/certificate-transparency-go@master` in your project? Followed by `go mod tidy`, I believe that should make the grpc/naming dependency go away, and it would be done under your control?

**Comment by allenpetersen** [comment]
Would it be possible to make a v1.1.2 release from a branch that only updates the `etcd` dependency?

I've been working on getting rid of this broken version of `etcd` from our dependency tree and the last place it is coming in is via `certificate-transparency-go` as an indirect dependency.

We are bringing in `certificate-transparency-go` via the `github.com/cloudflare/cfssl` project. That project has multiple issues raised due to this dependency problem. I'm sure that project would be happy by a new version of `certificate-transparency-go`

**Comment by vvakame** [comment]
I agree with allenpetersen-san's comment.
I understand that the current master / HEAD contains various BREAKING CHANGEs.

My project does not use this repository directly.

```
$ go mod why github.com/google/certificate-transparency-go
# github.com/google/certificate-transparency-go
github.com/vvakame/myproject
github.com/duo-labs/webauthn/protocol
github.com/duo-labs/webauthn/metadata
github.com/cloudflare/cfssl/revoke
github.com/cloudflare/cfssl/helpers
github.com/google/certificate-transparency-go
```

I think it will be difficult to get all the libraries in the middle to use master branch.
I hope if the breaking changes are finished, I'd like you to release v2. 😉

**Comment by vvakame** [comment]
@pphaneuf any update...?

**Comment by pavelkalinnikov** [comment]
Has the `v1.1.2` release [here](https://github.com/google/certificate-transparency-go/releases) solved your issue?

**Comment by pavelkalinnikov** [comment]
If not, we probably will have another release soon (this/next week).
