### ISSUE TITLE
trillian/ctfe: get-sth-consistency API leaks Go internal error messages when misused

### ISSUE THREAD

**Issue by phad** [google/certificate-transparency-go#81]
Example:
$ curl "ct.googleapis.com/logs/argon2020/ct/v1/get-sth-consistency?first=1000&last=1000"
Bad Request
failed to parse consistency range: strconv.ParseInt: parsing "": invalid syntax

'last' is not a valid URL query parameter for this API (it should be 'second').

I suspect the issue is in func parseGetSTHConsistencyRange

**Comment by daviddrysdale** [comment]
Fixed in #211
