### ISSUE TITLE
Code duplication between client.LogClient.GetEntries and scanner.Scanner.processEntry

### ISSUE THREAD

**Issue by Bren2010** [google/certificate-transparency-go#84]
`Scanner` re-implements `LogClient.GetEntries` with better (more granular) error handling and asynchronous processing. We should implement a method on `LogClient` that supports this use-case better, rather than copy-pasting the code.

**Comment by daviddrysdale** [comment]
@Bren2010's suggestion in pull #79 is a method like:
```go
LogClient.GetEachEntry(ctx context.Context, start, end int64, each func(ct.LogEntry, error)) error 
```

**Comment by daviddrysdale** [comment]
Actually, the callback-based entrypoint might not be needed -- just moving the `LogEntry` population code into a `ct.LogEntryFromLeaf()` entrypoint means that it's only a few lines to convert `GetRawEntries` results to parsed results (and get the errors along the way).
