### ISSUE TITLE
Provide API to retrieve CT Log server's original HTTP response where client.LogClient calls fail

### ISSUE THREAD

**Issue by phad** [google/certificate-transparency-go#89]
e.g. if the server returns garbled JSON, or some intermediate server replaces the JSON response with an error page, then it would be useful for the client to be able to access the raw HTTP response.

One way of doing this would be to define an error struct to be returned by `jsonclient.GetAndParse` that contains the `http.Response` rather than have `GetAndParse` return the body and a simple error as it does now.

Another way would be to leave `jsonclient.GetAndParse` as it is and define a richer error struct in the client package that `client.LogClient` can return from the `GetFoo` calls.

Note; 

1.  something like the above would be useful also in the `jsonclient.PostAndParse` API and the `client.Add{Pre}Chain` APIs that use it
2.  it would be good to be able to inspect the raw response even in successful cases.

**Comment by daviddrysdale** [comment]
As of #91, `client.LogClient` can now return errors of type `RspError` which include the body in them.
