### ISSUE TITLE
How to use this (certificate transparency go) project to build a CT server locally and upload certificates to obtain CT logs? 

### ISSUE THREAD

**Issue by zhen1129** [google/certificate-transparency-go#895]
hi，How to use this (certificate transparency go) project to build a CT server locally and upload certificates to obtain CT logs? What should I do? This is the first time I use the programming language of golang. Please be sure to tell me

**Comment by pavelkalinnikov** [comment]
Hi. Sorry, we can't help you much in learning Go, but you CT-specific question is also not very clear and contradicts itself. Please be clear on what you are trying to solve.

I am closing this for now, feel free to reopen when you have a more concrete question.

**Comment by K0zero** [comment]
I'm sorry, but I'm having this problem too.
I also want to deploy a CT server on my school's LAN servers to do some experiments of my own 
How can I deploy it locally? Thank you very much!

**Comment by roger2hk** [comment]
Thank you very much for your interest in CT. Please refer to the [Deployment](https://github.com/google/certificate-transparency-go/blob/master/trillian/README.md#deployment) section in the README.

**Comment by K0zero** [comment]
thanks a lot that's what i want
