### ISSUE TITLE
Updating chromepolicy.go

### ISSUE THREAD

**Issue by jsha** [google/certificate-transparency-go#906]
Chrome's CT policy is changing, effective for certificates issued on-or-after April 15: https://groups.google.com/a/chromium.org/g/ct-policy/c/507lPdbbwSk/m/JpxJEtrQAwAJ. Specifically, it removes the "one Google log" requirement in favor of (roughly paraphrasing) "2 logs with distinct operators."

I see https://github.com/google/certificate-transparency-go/blob/master/ctpolicy/chromepolicy.go hasn't been updated in a while. Are there plans to update that, and the corresponding submission logic, to match the new Chrome CT policy?

Thanks!

**Comment by breadyzhang** [comment]
I don't believe the policy has been updated yet. I can start taking a look at it and work towards updating the Chrome CT policy.
