### ISSUE TITLE
Sparse Fieldsets or similar?

### ISSUE THREAD

**Issue by jmrenshaw** [google/certificate-transparency-go#945]
I am doing some experimentation using the CloudFlare Nimbus CT log which I believe is built on this project.  Is it possible to only retrieve specific fields in the responses using sparse fieldsets (https://jsonapi.org/format/#fetching-sparse-fieldsets) or something similar?  I only want to retrieve the leaf_input field in a get-entries request and the extra_data field is typically quite large so I would like to exclude it to reduce wasted time and bandwidth.
I have used the following parameter in my HTTP GET which returns a valid response but does not change the contents (i.e. I still receive both leaf_input and extra_data).
?fields[entries]=leaf_input

**Comment by pphaneuf** [comment]
@roger2hk is correct, the CTFE server only implements [RFC 6962](https://datatracker.ietf.org/doc/html/rfc6962), it does not use or implement JSON:API in any way.

**Comment by jmrenshaw** [comment]
Thanks both for your swift and thorough response. @roger2hk if I had the time and the talent to implement the JSON API on top I would, but unfortunately I will just have to put up with the extra_data!

**Comment by pavelkalinnikov** [comment]
This is a good idea though, and could be a feature on top of RFC 6962 that our logs provide.
