### ISSUE TITLE
Is EKU filtering stable enough to be used by a production log?

### ISSUE THREAD

**Issue by pgporada** [google/certificate-transparency-go#974]
Based on discussion at https://groups.google.com/a/chromium.org/g/ct-policy/c/b0H8PQ_ssII, we're considering enabling EKU filtering for the Let's Encrypt Oak and Sapling logs. However, checking the changelog shows an old note that 

> warning It is not yet recommended to enable this option in a production CT Log!
https://github.com/google/certificate-transparency-go/blob/master/CHANGELOG.md#eku-filtering

Is this now fine to enable?

**Comment by phbnf** [comment]
We have been using the "ServerAuth" EKU filtering on our production logs for more than 5 months now, so it's fine to enable. We should probably remove this warning, thank you very much for the heads up.
