### ISSUE TITLE
Loglists are offline - v3 urls needed

### ISSUE THREAD

**Issue by d-Rickyy-b** [google/certificate-transparency-go#988]
The [loglist URLs](https://pkg.go.dev/github.com/google/certificate-transparency-go@v1.1.3/loglist#pkg-constants) are offline.

https://www.gstatic.com/ct/log_list/log_list.json
https://www.gstatic.com/ct/log_list/all_logs_list.json
https://www.gstatic.com/ct/log_list/log_list.sig

Seems like the new URLs are 
https://www.gstatic.com/ct/log_list/v3/log_list.json
https://www.gstatic.com/ct/log_list/v3/all_logs_list.json
https://www.gstatic.com/ct/log_list/v3/log_list.sig

They might need different parsing than before?

**Comment by d-Rickyy-b** [comment]
https://github.com/CaliDog/certstream-server/pull/92/files

Yeah, seems like the logs are now within the "operators" key.

**Comment by pphaneuf** [comment]
This is as per the following: https://groups.google.com/a/chromium.org/g/ct-policy/c/zejEtWAJtEA/m/IYxEY8uMAQAJ

**Comment by roger2hk** [comment]
The v1 log list was removed in https://github.com/google/certificate-transparency-go/pull/977 on Sep 10 but the latest release was still on May 14. A new release will be created to resolve this issue.

**Comment by roger2hk** [comment]
The latest release can be found at https://github.com/google/certificate-transparency-go/releases/tag/v1.1.4 and https://pkg.go.dev/github.com/google/certificate-transparency-go@v1.1.4.
